---
title: "visualization2"
author: "Rachel Lee"
date: "3/18/2020"
output: html_document
---

```{r visualization_part2}
library(tidyverse)
library(ggridges)
library(patchwork)


weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df %>%
  ggplot(aes(x=tmin, y=tmax)) +
  geom_point(aes(color=name), alpha=0.5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  )+ 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15ºC", "0", "15"),
    limits = c(-20, 30)) + 
  scale_y_continuous(
    trans = "sqrt", 
    position = "right")



ggp_temp_plot = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package"
  ) + 
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )

ggp_temp_plot 

ggp_temp_plot + 
  theme(legend.position = "bottom")

ggp_temp_plot +
  theme_classic() +
  theme(legend.position = "bottom" ) 

#learning assessment

ggplot(weather_df, aes(x=date, y=tmax)) +
  geom_smooth( se = FALSE ) +
  geom_point(aes(color=name, size=prcp), alpha=0.75) +
  labs(
    title = "Temperature plot",
    x = "date",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") +
  theme_classic() +
  theme(legend.position = "bottom")


ggplot(weather_df, aes(x=date, y=tmax)) +
  geom_smooth( se = FALSE ) +
  geom_point(aes(color=name, size=prcp), alpha=0.75) +
  labs(
    title = "Temperature plot",
    x = "date",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") +
  viridis::scale_color_viridis(discrete = TRUE) + 
  theme_classic() +
  theme(legend.position = "bottom")

```



```{r setting_options}

library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)


theme_set(theme_bw() + theme(legend.position = "bottom"))

```



```{r}

#separate dataset called "central_park"

central_park = 
  weather_df %>%
  filter(name == "CentralPark_NY")

#separate dataset called "waikiki" 

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")


ggplot(waikiki, aes (x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)


###########
#Patchwork#
###########

tmax_tmin_p = 
  weather_df %>%
  ggplot(aes(x = tmax, y = tmin, color = name)) +
      #no need to call the dataset because it's mentioned above
  geom_point(alpha = 0.5) +
  theme(legend.position = "none")


prcp_dens_p =
  weather_df %>%
  filter(prcp > 0 ) %>% #only plot prcp > 0
  ggplot(aes(x = prcp, fill = name)) +
      #density curve yaxis is always probability
      #"fill" necessary for density curves
  geom_density(alpha = 0.5) +
  theme(legend.position = "none")
  

tmax_date_p =
  weather_df %>%
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none")


#patchwork positions your plots as you order them
    #top left = tmax_tmin_p + top right = prcp_dense_p
    #bottom = tmax_date_p
(tmax_tmin_p + prcp_dens_p) / tmax_date_p



###################
#Data Manipulation#
###################


#reordering levels of a factor variable "manually" 

weather_df %>%
  mutate(name = forcats::fct_relevel(name, c("CentralPark_NY", "Waterhole_WA", "Waikiki_HA")))  %>%
  ggplot(aes(x=name, y=tmax)) +
  geom_violin(aes(fill=name), color = "blue", alpha = 0.5)+
  theme(legend.position = "bottom")


#reordering levels of a factor varible according to "tmax" values

weather_df %>%
  mutate(name = forcats::fct_reorder(name, tmax)) %>%
  ggplot(aes(x = name, y=tmax)) +
  geom_violin(aes(fill=name), color = "blue", alpha=0.5)+
  theme(legend.position = "bottom")
  

weather_df %>%
  select(name, tmax, tmin) %>%
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temperature") %>%
  ggplot(aes(x= temperature)) +
  geom_density(aes(fill= observation), alpha = .5) +
  facet_grid(~name) + #separate grids by "name"
   viridis::scale_fill_viridis(discrete = TRUE)


pulse_data = 
  haven::read_sas("/Users/rachellee/Desktop/ds_data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  select(id, visit, everything()) %>%
  mutate(visit = recode(visit, "bl" = "00m"),
         visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id,visit)

ggplot(pulse_data, aes(x = visit, y = bdi)) +
  geom_boxplot()

###############################################

pup_data = 
  read_csv("/Users/rachellee/Desktop/ds_data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))


litter_data = 
  read_csv("/Users/rachellee/Desktop/ds_data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names()%>%
  separate(group, into = c("dose", "day_of_tx"), sep=3) %>%  #making a single column into multiple columns
  mutate(wt_gain = gd18_weight - gd0_weight,
         day_of_tx = as.numeric(day_of_tx))

fas_data = left_join(pup_data, litter_data, by = "litter_number")

fas_data %>%
select(sex, dose, day_of_tx, pd_ears:pd_walk) %>%
pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome",
    values_to = "pn_day") %>%
  drop_na() %>%
  mutate(outcome = forcats::fct_reorder(outcome, day_of_tx, median)) %>%
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)
 


```

